#!/usr/bin/env node

const [,,version] = process.argv

if (!/^[0-9]+\.[0-9]+\.[0-9]+$/.test (version))
    throw new Error (`Invalid version "${ version }". Please input version number in X.Y.Z format.`)

require ('child_process')
    .execSync (`npm version ${ version } && git push && git push origin v${ version }`)
    .toString ()

console.info ('Released v' + version)
